# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenMapMatMult <- function(A, B) {
    .Call('_RcppFunctions_eigenMapMatMult', PACKAGE = 'RcppFunctions', A, B)
}

malaria_ode_cpp <- function(t, x, params) {
    .Call('_RcppFunctions_malaria_ode_cpp', PACKAGE = 'RcppFunctions', t, x, params)
}

